function display_pola(E,Ea,Ea_std,Ec,Ec_std,CD,CD_std,data_all,data_palier,eff)
% display_pola(E,Ea,Ec,CD,CD_std,data_all,data_palier,eff)
% Plot the polarisation curve and the data generated by ec lab


gcf;
clf

%--------------------------------------------------------------------------
subplot(223)
errorbar(-CD/0.05,E,CD_std/0.05,'horizontal')
hold on
errorbar(-CD/0.05,Ea,Ea_std,Ea_std,CD_std/0.05,CD_std/0.05)
errorbar(-CD/0.05,Ec,Ec_std,Ec_std,CD_std/0.05,CD_std/0.05)
title('courbe pola')
ylabel('Tension (V)')
xlabel('Densité de courant (mA/cm^2)')
legend('DeltaV','Ea','Ec')
grid on

%--------------------------------------------------------------------------
subplot(224)
plot(E,eff,E,eff.*E/1.5)
title('efficacité')
ylabel('Efficacité (%)')
xlabel('Tension pile (V)')
legend('Efficacité coulombique','Efficacité total')
grid on


%--------------------------------------------------------------------------
subplot(2,2,[1 2])
yyaxis left
plot(data_all(:,1),-data_all(:,2)*1000,data_palier(:,1),-data_palier(:,2)*1000,'o')
ylim([0 max(-data_palier(:,2))*1.2*1000])
yyaxis right
plot(data_all(:,1),data_all(:,3),data_palier(:,1),data_palier(:,3),'o')
hold on
plot(data_all(:,1),data_all(:,4),'b-',data_palier(:,1),data_palier(:,4),'bo')
plot(data_all(:,1),data_all(:,5),'m-',data_palier(:,1),data_palier(:,5),'mo')
title('résumé de la manip')

ylim([0 1.3])
ylabel('Tension (V)')
xlabel('Temps (s)')
grid on
legend('I','Points moyennés','DeltaV','Points moyennés','Ea','Points moyennés','Ec','Points moyennés')
end